name = "tmc-file-transfer"
compatibility_date = "2024-08-21"

# Pages configuration
pages_build_output_dir = "./dist"

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
MAX_FILE_SIZE = "5368709120"  # 5GB in bytes (supports large files via multipart upload)
ALLOWED_ORIGINS = "https://upload.frisson.social"
TURNSTILE_SITE_KEY = "0x4AAAAAABuG5x3RAnK97btK"
TURNSTILE_SECRET_KEY = "0x4AAAAAABuG51VCoK0GijK7ULELVtkO4nY"
CLOUDFLARE_ZONE_ID = "97d4cbc4306ea586a3a49ad0e990bbc1"

# D1 Database binding for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "tmc-file-transfer"
database_id = "dde71e0c-af96-4e8a-9f4b-c2f89b2c2a30"

# R2 Storage binding for production
[[env.production.r2_buckets]]
binding = "TRANSFER_BUCKET"
bucket_name = "tmc-transfers"

[env.preview.vars]
ENVIRONMENT = "preview"
MAX_FILE_SIZE = "5368709120"  # 5GB in bytes (supports large files via multipart upload)
ALLOWED_ORIGINS = "*"
TURNSTILE_SITE_KEY = "1x00000000000000000000AA"  # Test key for preview
TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"  # Test key for preview

# D1 Database binding for preview
[[env.preview.d1_databases]]
binding = "DB"
database_name = "tmc-file-transfer"
database_id = "dde71e0c-af96-4e8a-9f4b-c2f89b2c2a30"

# R2 Storage binding for preview
[[env.preview.r2_buckets]]
binding = "TRANSFER_BUCKET"
bucket_name = "tmc-transfers"

# KV namespace for caching (optional)
#[[kv_namespaces]]
#binding = "CACHE"
#id = "your-kv-namespace-id"
#preview_id = "your-kv-preview-id"

# Analytics Engine for logging (commented out - needs setup)
#[[analytics_engine_datasets]]
#binding = "ANALYTICS"
#dataset = "tmc_file_transfer_logs"

# Queue for background processing (optional)
#[[queues]]
#binding = "CLEANUP_QUEUE"
#queue = "file-cleanup-queue"

# Durable Objects (optional, for advanced features)
#[[durable_objects.bindings]]
#name = "RATE_LIMITER"
#class_name = "RateLimiter"
#script_name = "tmc-file-transfer"

# Note: Pages doesn't support [limits], [build], or [[rules]] sections
# These are handled automatically by the Pages platform

# Headers configuration
[env.production.headers]
"/*" = [
  { name = "X-Frame-Options", value = "DENY" },
  { name = "X-Content-Type-Options", value = "nosniff" },
  { name = "X-XSS-Protection", value = "1; mode=block" },
  { name = "Referrer-Policy", value = "strict-origin-when-cross-origin" },
  { name = "Strict-Transport-Security", value = "max-age=31536000; includeSubDomains" },
  { name = "Permissions-Policy", value = "geolocation=(), microphone=(), camera=()" }
]

# Cache configuration for static assets
[env.production.caching]
"/assets/*" = { edge_ttl = 31536000, browser_ttl = 31536000 }
"/favicon*" = { edge_ttl = 31536000, browser_ttl = 31536000 }
"*.js" = { edge_ttl = 31536000, browser_ttl = 31536000 }
"*.css" = { edge_ttl = 31536000, browser_ttl = 31536000 }