name = "tmc-cleanup-worker"
main = "dist/index.js"
compatibility_date = "2024-08-21"

# Worker configuration
[build]
command = "npm run build"

# Environment variables
[vars]
ENVIRONMENT = "production"
DEBUG = "false"
BATCH_SIZE = "50"
MAX_EXECUTION_TIME = "25000"
VACUUM_INTERVAL = "604800"

# Cron triggers - runs every 6 hours
[[triggers.crons]]
cron = "0 */6 * * *"

# Production environment
[env.production]
name = "tmc-cleanup-worker"

[env.production.vars]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "warn"

# Production database binding
[[env.production.d1_databases]]
binding = "DB"
database_name = "tmc-file-transfer"
database_id = "your-production-database-id"

# Production R2 binding
[[env.production.r2_buckets]]
binding = "TRANSFER_BUCKET"
bucket_name = "tmc-transfers"

# Development environment
[env.development]
name = "tmc-cleanup-worker-dev"

[env.development.vars]
ENVIRONMENT = "development"
DEBUG = "true"
LOG_LEVEL = "debug"
BATCH_SIZE = "10"

# Development database binding
[[env.development.d1_databases]]
binding = "DB"
database_name = "tmc-file-transfer-dev"
database_id = "your-dev-database-id"

# Development R2 binding
[[env.development.r2_buckets]]
binding = "TRANSFER_BUCKET"
bucket_name = "tmc-transfers-dev"

# Staging environment
[env.staging]
name = "tmc-cleanup-worker-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
DEBUG = "false"
LOG_LEVEL = "info"

# Staging database binding
[[env.staging.d1_databases]]
binding = "DB"
database_name = "tmc-file-transfer-staging"
database_id = "your-staging-database-id"

# Staging R2 binding
[[env.staging.r2_buckets]]
binding = "TRANSFER_BUCKET"
bucket_name = "tmc-transfers-staging"